In [1]:
import pandas as pd
import numpy as np

In [2]:
# https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

# https://github.com/mwaskom/seaborn-data/tree/master

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

# kaggle
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [3]:
df = pd.read_csv(titanic_dataset_github_url)

In [4]:
df[(df['Sex'] == 'female') & (df['Survived'] == 1)].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [5]:
female_survivors_subset = df[(df['Sex'] == 'female') & (df['Survived'] == 1)][['Name', 'Age']]
female_survivors_subset.head()

                                                Name   Age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0

In [6]:
female_survivors_subset_loc = df.loc[(df['Sex'] == 'female') & (df['Survived'] == 1), ['Name', 'Age']]
female_survivors_subset_loc.head()

                                                Name   Age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0

In [ ]:
#df.loc[rows, columns]

df.loc[0, ['Cabin']]

Cabin    NaN
Name: 0, dtype: object

In [8]:
# Number of survivors
print(len(df[df['Survived'] == 1]))

342

# slicing rows and columns

In [9]:
df.loc[0:4, ['Name', 'Age']]

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [10]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
# I want first 3 rows and first 2 columns

# --> numbers for index

df.iloc[0:3, 0:2]

   PassengerId  Survived
0            1         0
1            2         1
2            3         1

In [14]:
# First 3 rows and selected columns by index
# --> column 1,3
df.iloc[0:4, [1,3]]

   Survived                                               Name
0         0                            Braund, Mr. Owen Harris
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1                             Heikkinen, Miss. Laina
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)

In [15]:
df.iloc[0:3, [3, 1]]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1

In [16]:
df.loc[0:2, ['Name', 'Survived']]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1

In [17]:
df.loc[0:2, ['Survived', 'Name']]

   Survived                                               Name
0         0                            Braund, Mr. Owen Harris
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1                             Heikkinen, Miss. Laina

In [18]:
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [ ]:
subset = df[df['Sex'] == 'male'] # might create a view 
subset['Age'] = subset['Age'] + 1 # Increase the age of every male passenger in subset by 1.
print(subset.head(2))
print(df.head(2))

   PassengerId  Survived  Pclass                      Name   Sex   Age  SibSp  \
0            1         0       3   Braund, Mr. Owen Harris  male  23.0      1
4            5         0       3  Allen, Mr. William Henry  male  36.0      0

   Parch     Ticket  Fare Cabin Embarked
0      0  A/5 21171  7.25   NaN        S
4      0     373450  8.05   NaN        S
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1

   Parch     Ticket     Fare Cabin Embarked
0      0  A/5 21171   7.2500   NaN        S
1      0   PC 17599  71.2833   C85        C

/var/folders/hf/xkx_j1zs7vv6_tl_vsjmk_tr0000gn/T/ipykernel_55487/2272092673.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset['Age'] = subset['Age'] + 1

In [22]:
subset = df[df['Sex'] == 'male'].copy()
subset['Age'] += 1
print(subset)

     PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male
4              5         0       3        Allen, Mr. William Henry  male
5              6         0       3                Moran, Mr. James  male
6              7         0       1         McCarthy, Mr. Timothy J  male
7              8         0       3  Palsson, Master. Gosta Leonard  male
..           ...       ...     ...                             ...   ...
883          884         0       2   Banfield, Mr. Frederick James  male
884          885         0       3          Sutehall, Mr. Henry Jr  male
886          887         0       2           Montvila, Rev. Juozas  male
889          890         1       1           Behr, Mr. Karl Howell  male
890          891         0       3             Dooley, Mr. Patrick  male

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0    23.0      1      0         A/5 21171   7.2500   NaN        S
4    36.0      0      0            373450   8.0500   NaN        S
5     NaN      0      0            330877   8.4583   NaN        Q
6    55.0      0      0             17463  51.8625   E46        S
7     3.0      3      1            349909  21.0750   NaN        S
..    ...    ...    ...               ...      ...   ...      ...
883  29.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
884  26.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
886  28.0      0      0            211536  13.0000   NaN        S
889  27.0      0      0            111369  30.0000  C148        C
890  33.0      0      0            370376   7.7500   NaN        Q

[577 rows x 12 columns]

In [23]:
# iloc --> copy
# loc --> may be view
# df[...] --> may be view
# df 
# .copy()

In [24]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df_by_name = df.set_index('Name') # it will set the index by name
df_by_name.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [27]:
print(df_by_name.loc['Allen, Mr. William Henry'])

PassengerId         5
Survived            0
Pclass              3
Sex              male
Age              35.0
SibSp               0
Parch               0
Ticket         373450
Fare             8.05
Cabin             NaN
Embarked            S
Name: Allen, Mr. William Henry, dtype: object

In [28]:
df_by_name = df_by_name.reset_index()
df_by_name.head()

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df_by_name.reset_index(inplace=True) #inplace=True means modified df_by_name iteself and if we don't do inplace=True the we have to reassign df_by_name = df_by_name.reset_index()
df_by_name.head()

,index,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [30]:
df_by_name = df.set_index('Name')
df_by_name = df_by_name.reset_index()
df_by_name.head()

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

# Reindex

-- reindex() is used to change the order of rows or columns and/or add missing labels according to the new index you provide.

In [31]:
sales_jan = pd.DataFrame({
    'Sales': [250, 400, 300]
}, index=['Store_A', 'Store_B', 'Store_C'])

sales_jan

         Sales
Store_A    250
Store_B    400
Store_C    300

In [32]:
sales_feb = pd.DataFrame({
    'Sales': [260, 310]
}, index=['Store_A', 'Store_C'])

sales_feb

         Sales
Store_A    260
Store_C    310

In [33]:
common_index = sales_jan.index

In [34]:
sales_feb_aligned = sales_feb.reindex(common_index)

In [35]:
sales_feb_aligned

         Sales
Store_A  260.0
Store_B    NaN
Store_C  310.0

In [36]:
sales_diff = sales_feb_aligned['Sales'] - sales_jan['Sales']

sales_diff

Store_A    10.0
Store_B     NaN
Store_C    10.0
Name: Sales, dtype: float64

In [37]:
sales_feb_aligned = sales_feb.reindex(common_index, fill_value=0)

sales_feb_aligned

         Sales
Store_A    260
Store_B      0
Store_C    310

In [38]:
sales_diff = sales_feb_aligned['Sales'] - sales_jan['Sales']

sales_diff

Store_A     10
Store_B   -400
Store_C     10
Name: Sales, dtype: int64

In [39]:
sales_feb_new = pd.DataFrame({
    'Sales': [260, 310, 100]
}, index=['Store_A', 'Store_C', 'Store_D'])

sales_feb_new

         Sales
Store_A    260
Store_C    310
Store_D    100

In [40]:
common_index = list(set(list(sales_jan.index) + list(sales_feb_new.index)))

In [41]:
common_index

['Store_D', 'Store_C', 'Store_A', 'Store_B']

In [42]:
sales_jan_aligned = sales_jan.reindex(common_index, fill_value=0)

sales_jan_aligned

         Sales
Store_D      0
Store_C    300
Store_A    250
Store_B    400

In [43]:
sales_feb_new_aligned = sales_feb_new.reindex(common_index, fill_value=0)

sales_feb_new_aligned

         Sales
Store_D    100
Store_C    310
Store_A    260
Store_B      0

In [44]:
to_check = 'Store_C'
print(sales_feb_new_aligned.loc[to_check])
print(sales_jan_aligned.loc[to_check])

Sales    310
Name: Store_C, dtype: int64
Sales    300
Name: Store_C, dtype: int64

# for column

In [45]:
source_a = pd.DataFrame({
    'Product': ['Laptop', 'Tablet', 'Phone'],
    'Price': [1000, 500, 800],
    'Stock': [30, 50, 100]
})

source_a

  Product  Price  Stock
0  Laptop   1000     30
1  Tablet    500     50
2   Phone    800    100

In [46]:
source_b = pd.DataFrame({
    'Price': [980, 520, 810],
    'Product': ['Laptop', 'Tablet', 'Phone']
})

source_b

   Price Product
0    980  Laptop
1    520  Tablet
2    810   Phone

In [47]:
aligned_b = source_b.reindex(columns=source_a.columns, fill_value = 0)

aligned_b

  Product  Price  Stock
0  Laptop    980      0
1  Tablet    520      0
2   Phone    810      0

# iteration in pandas

In [48]:
df = pd.DataFrame({
    'Name' : ['heartine', 'gagan', 'gavin'],
    'Age' : [25, 20, 23],
    'City' : ['Delhi', 'Mumbai', 'Chennai'],
})

In [49]:
for index, row in df.iterrows():
    print(f"{index}: {row['Name']} lives in {row['City']} and is {row['Age']} years old.")

0: heartine lives in Delhi and is 25 years old.
1: gagan lives in Mumbai and is 20 years old.
2: gavin lives in Chennai and is 23 years old.

In [50]:
for row in df.itertuples():
    print(f"{row.Name} lives in {row.City}, and is {row.Age} years old.", end='\n\n')

heartine lives in Delhi, and is 25 years old.

gagan lives in Mumbai, and is 20 years old.

gavin lives in Chennai, and is 23 years old.

In [51]:
for col in df.columns:
    print(f"Column: {col}")
    print(df[col].values, end='\n\n')

Column: Name
['heartine' 'gagan' 'gavin']

Column: Age
[25 20 23]

Column: City
['Delhi' 'Mumbai' 'Chennai']

# Condition based column creation using custom logic

In [52]:
df.head()

       Name  Age     City
0  heartine   25    Delhi
1     gagan   20   Mumbai
2     gavin   23  Chennai

In [ ]:
values = []

for idx, row in df.iterrows():
    if row['Age']< 30:
        values.append('young')
    else:
        values.append('senior')

df['Category'] = values # Add new column

In [54]:
df

       Name  Age     City Category
0  heartine   25    Delhi    young
1     gagan   20   Mumbai    young
2     gavin   23  Chennai    young

In [55]:
# vectorized using apply

df = pd.DataFrame({
    'Name' : ['heartine', 'gagan', 'gavin'],
    'Age' : [25, 20, 23],
    'City' : ['Delhi', 'Mumbai', 'Chennai'],
})

In [56]:
df['Categories'] = df['Age'].apply(lambda age : 'young' if age < 30 else 'senior')

In [57]:
df

       Name  Age     City Categories
0  heartine   25    Delhi      young
1     gagan   20   Mumbai      young
2     gavin   23  Chennai      young

In [ ]:
# iterrows < itertuples < apply

# Sort