# Pandas

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# Series in pandas
-- it is one dimension labelled array

In [78]:
import pandas as pd
import numpy as np

In [79]:
s1 = pd.Series([10,20,30,40,50,60])
print(s1)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [80]:
s2 = pd.Series([10,20,30,40,50,60], index=['a', 'b', 'c', 'd', 'e', 'f'], name="scores")
print(s2)

a    10
b    20
c    30
d    40
e    50
f    60
Name: scores, dtype: int64

In [81]:
# create series from dict

data = {'a' : 10, 'b' : 20, 'c' : 30, 'd' : 40}
s3 = pd.Series(data)
print(s3)

a    10
b    20
c    30
d    40
dtype: int64

In [82]:
np_array = np.array([10,20,30,40,50,60])
s4 = pd.Series(np_array)
print(s4)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [83]:
# create series from dict
data = {'a':10, 'b':20, 'c':1.11, 'd':True}
s5 = pd.Series(data)
print(s5)

a      10
b      20
c    1.11
d    True
dtype: object

In [84]:
# create series from dict
data = {'a':10, 'b':20, 1:1.11, 2:True}
s6 = pd.Series(data)
print(s6)

a      10
b      20
1    1.11
2    True
dtype: object

In [86]:
# create series from dict
data = {'a':10, 'b':20, 'c':30, 'd':40}
s7 = pd.Series(data, name="scores")
print(s7)

a    10
b    20
c    30
d    40
Name: scores, dtype: int64

In [87]:
# 2D, 3D, 10D, 100D --> [[1,2], [23,4], [45, 56]] --> flatten --> np.flatten() --> []

In [88]:
print(s7.index)
print(s7.values)
print(s7.dtypes)
print(s7.name)
print(s7.shape)

Index(['a', 'b', 'c', 'd'], dtype='object')
[10 20 30 40]
int64
scores
(4,)

# Series indexing and slicing

In [89]:
data = {'a':10, 'b':20, 'c':30, 'd':40}
s7 = pd.Series(data, name="scores")
print(s7)

a    10
b    20
c    30
d    40
Name: scores, dtype: int64

In [91]:
print(s7.values[0]) # positional index

10

In [92]:
print(s7.loc[0]) #indexing

KeyError: 0

In [93]:
print(s7[0]) #indexing or lable indexing

10

/var/folders/hf/xkx_j1zs7vv6_tl_vsjmk_tr0000gn/T/ipykernel_37493/1420132924.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s7[0]) #indexing or lable indexing

In [95]:
print(s7.loc['a']) #indexing

10

In [96]:
print(s7.iloc[0]) # Positional indexing

10

In [98]:
print(s7.loc[['a','b']]) #indexing

a    10
b    20
Name: scores, dtype: int64

In [99]:
print(s7.iloc[[0,1]]) # Positional indexing

a    10
b    20
Name: scores, dtype: int64

In [100]:
print(s7.iloc[0:2]) # Positional indexing (exclusive)

a    10
b    20
Name: scores, dtype: int64

In [101]:
# create series from dict

data = {'a' : 10, 'b' : 20, 'c' : 30, 'd' : 40, 0 : 100, 1 : 101, 2 : 400, 6:700}
s9 = pd.Series(data, name='scores')
print(s9)

a     10
b     20
c     30
d     40
0    100
1    101
2    400
6    700
Name: scores, dtype: int64

In [102]:
s9.loc[0:2] # inclusive

0    100
1    101
2    400
Name: scores, dtype: int64

In [103]:
# Slicing
# - loc [start, end] : end is inclusive
# - iloc [start, end]  :end is exclusive

# dataframe

-- A DataFrame is a 2-dimensional data structure in Pandas used to store data in rows and columns, similar to an Excel spreadsheet or a database table.

In [104]:
data = {
    'Name' : ['Rakesh', 'Mukesh', 'Suraj'],
    'Age' :[20, 22, 25],
    'City' : ['Delhi', 'Bihar', 'Sitamarhi']
}

In [106]:
df = pd.DataFrame(data)
print(df)

     Name  Age       City
0  Rakesh   20      Delhi
1  Mukesh   22      Bihar
2   Suraj   25  Sitamarhi

In [107]:
data_1 = [
    {'Name':'Rakesh', 'Age':'20', 'City':'Delhi'},
    {'Name':'Mukesh', 'Age':'23', 'City':'Bihar'},
    {'Name':'Suraj', 'Age':'25', 'City':'Sitamarhi'}
]

In [108]:
df_1 = pd.DataFrame(data_1)
print(df_1)

     Name Age       City
0  Rakesh  20      Delhi
1  Mukesh  23      Bihar
2   Suraj  25  Sitamarhi

In [109]:
arr_data = np.array([[1,2],[3,4], [5,6]])

In [111]:
df_2 = pd.DataFrame(arr_data)
print(df_2)

   0  1
0  1  2
1  3  4
2  5  6

In [112]:
df_2 = pd.DataFrame(arr_data, columns=['A', 'B'])
print(df_2)

   A  B
0  1  2
1  3  4
2  5  6

# Accessing the values

In [113]:
data = {
    'Name' : ['Rakesh', 'Mukesh', 'Suraj'],
    'Age' :[20, 22, 25],
    'City' : ['Delhi', 'Bihar', 'Sitamarhi']
}
df_4 = pd.DataFrame(data)

In [115]:
print(df_4)

     Name  Age       City
0  Rakesh   20      Delhi
1  Mukesh   22      Bihar
2   Suraj   25  Sitamarhi

In [116]:
type(df_4)

pandas.core.frame.DataFrame

In [117]:
print(df_4['Name'])
print('=='*40)
print(df_4[['Name', 'Age']])
print('=='*40)
print(df_4.loc[0])
print('=='*40)
print(df_4.loc[0:1]) # Inclusive
print('=='*40)
print(df_4.iloc[0])
print('=='*40)
print(df_4.iloc[0:1]) # Exclusive
print('=='*40)

0    Rakesh
1    Mukesh
2     Suraj
Name: Name, dtype: object
================================================================================
     Name  Age
0  Rakesh   20
1  Mukesh   22
2   Suraj   25
================================================================================
Name    Rakesh
Age         20
City     Delhi
Name: 0, dtype: object
================================================================================
     Name  Age   City
0  Rakesh   20  Delhi
1  Mukesh   22  Bihar
================================================================================
Name    Rakesh
Age         20
City     Delhi
Name: 0, dtype: object
================================================================================
     Name  Age   City
0  Rakesh   20  Delhi
================================================================================

# Working with real dataset

In [118]:
# https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

# https://github.com/mwaskom/seaborn-data/tree/master

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

# kaggle
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [122]:
df = pd.read_csv(titanic_dataset_github_url) #raw data

In [123]:
# preview of the dataframe

# 1st 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [124]:
# last 5 rows

df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [125]:
print(df.tail())

     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q

In [127]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [128]:
df['Survived']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [129]:
df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [130]:
df.loc[0] # first row

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [ ]:
df.loc[0, 'Name'] # name of the passenger at index 0 {.loc[row, column]}

'Braund, Mr. Owen Harris'

In [132]:
df.loc[0:4] # 5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [133]:
df.iloc[0] # 1st row

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [134]:
df.iloc[0:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [135]:
df.iloc[:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.iloc[0, 3] # position index meand 0->row, 3->col

'Braund, Mr. Owen Harris'

# Conditional Selection

In [138]:
# get all the rows where person age is greater than 70

# df[condition]
df[df['Age'] > 70]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [139]:
df[df['Age'] < 20]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [140]:
older_passengers = df[df['Age'] > 70]
older_passengers.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [145]:
# get all the females who surivived
df[(df['Sex'] == 'female') & (df['Survived'] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [146]:
# get all the females who surivived
female_surviors_subset = df[(df['Sex'] == 'female') & df['Survived'] == 1][['Name', 'Age']]
female_surviors_subset.head()

                                                Name   Age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0

In [147]:
female_surviors_subset.head(10)

                                                 Name   Age
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                              Heikkinen, Miss. Laina  26.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0
10                    Sandstrom, Miss. Marguerite Rut   4.0
11                           Bonnell, Miss. Elizabeth  58.0
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0
19                            Masselmani, Mrs. Fatima   NaN
22                        McGowan, Miss. Anna "Annie"  15.0

In [148]:
# total number of survivors

survived = len(df[df['Survived'] == 1])
notsurvived = len(df[df['Survived'] == 0])
print(notsurvived + survived)

891

In [149]:
survived/(notsurvived + survived)

0.3838383838383838

In [150]:
notsurvived/(notsurvived + survived)

0.6161616161616161